[versions]
minecraft     = "1.21.3"
fabric-loader = "0.16.9"
parchment     = "1.21:2024.07.28"
fabric-api    = "0.107.0+1.21.3"
fabric-kotlin = "1.11.0+kotlin.2.0.0"
permissions   = "0.3.3"
inject        = "2.2.2"

# Compatability depdendencies
carpet        = "1.4.158"
voicechat     = "fabric-1.21.3-2.5.25"
voicechat-api = "2.5.0"
vmp           = "0.2.0+beta.7.180+1.21.3"
c2me          = "0.3.0+beta.1.0+1.21.3"
servux        = "1.21.3-0.4.0-sakura.2"
syncmatica    = "1.21.3-sakura.10"
replay-studio = "4e670490d1"

# Plugins
fabric-loom   = "1.9-SNAPSHOT"
mod-publish   = "0.8.1"
shadow        = "8.1.1"
explosion     = "0.3.1"

[libraries]
minecraft        = { module = "com.mojang:minecraft"               , version.ref = "minecraft" }
fabric-loader    = { module = "net.fabricmc:fabric-loader"         , version.ref = "fabric-loader" }
fabric-api       = { module = "net.fabricmc.fabric-api:fabric-api" , version.ref = "fabric-api" }
fabric-kotlin    = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
permissions      = { module = "me.lucko:fabric-permissions-api"    , version.ref = "permissions" }
replay-studio    = { module = "com.github.ReplayMod:ReplayStudio"  , version.ref = "replay-studio" }
inject-api       = { module = "net.mcbrawls.inject:api"            , version.ref = "inject" }
inject-http      = { module = "net.mcbrawls.inject:http"           , version.ref = "inject" }
inject-fabric    = { module = "net.mcbrawls.inject:fabric"         , version.ref = "inject" }

# Compatability depdendencies
carpet           = { module = "com.github.gnembon:fabric-carpet"    , version.ref = "carpet" }
voicechat        = { module = "maven.modrinth:simple-voice-chat"    , version.ref = "voicechat" }
voicechat-api    = { module = "de.maxhenkel.voicechat:voicechat-api", version.ref = "voicechat-api" }
vmp              = { module = "maven.modrinth:vmp-fabric"           , version.ref = "vmp" }
c2me             = { module = "maven.modrinth:c2me-fabric"          , version.ref = "c2me" }
servux           = { module = "com.github.sakura-ryoko:servux"      , version.ref = "servux" }
syncmatica       = { module = "com.github.sakura-ryoko:syncmatica"  , version.ref = "syncmatica" }

[plugins]
fabric-loom          = { id = "fabric-loom", version.ref = "fabric-loom" }
mod-publish          = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
shadow               = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
explosion            = { id = "lol.bai.explosion", version.ref = "explosion"}